# Generated by Django 5.1.2 on 2024-10-26 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('conference', 'Conference'), ('concert', 'Concert'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('exhibition', 'Exhibition'), ('webinar', 'Webinar'), ('networking', 'Networking Event'), ('festival', 'Festival'), ('theater', 'Theater Performance'), ('film', 'Film Screening'), ('meetup', 'Meetup'), ('fundraiser', 'Fundraiser'), ('sport', 'Sporting Event'), ('class', 'Class'), ('retreat', 'Retreat'), ('hackathon', 'Hackathon'), ('fair', 'Fair'), ('open_house', 'Open House'), ('panel', 'Panel Discussion'), ('competition', 'Competition'), ('trade_show', 'Trade Show'), ('book_reading', 'Book Reading'), ('community_service', 'Community Service Event'), ('culinary', 'Culinary Event'), ('art_show', 'Art Show'), ('science_fair', 'Science Fair'), ('fashion_show', 'Fashion Show'), ('virtual_event', 'Virtual Event'), ('cultural_event', 'Cultural Event'), ('pet_expo', 'Pet Expo')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_event', to='events_app.event')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
